name: Draft

on:
  workflow_dispatch:
    inputs:
      announcementName:
        description: "Announcements to draft-deploy. ex: poll/2022-2023/Sondage de fin d'année"
        required: true

jobs:
  draft_deploy_webhooks:
    name: Draft deploy webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Draft deploy webhooks
        run: npm run deploy
        env:
          WEBHOOKURL_DRAFT: ${{ secrets.WEBHOOKURL_DRAFT }}

          WEBHOOK_AVATAR: ${{ secrets.WEBHOOK_AVATAR }}
          WEBHOOK_NAME: ${{ secrets.WEBHOOK_NAME }}

          DEPLOY_SERVER_ID: ${{ secrets.DEPLOY_SERVER_ID }}
          ANNOUNCEMENT_NAME: ${{ github.event.inputs.announcementName }}

          SECRET_0: ${{ secrets.SECRET_0 }}
          SECRET_1: ${{ secrets.SECRET_1 }}
          SECRET_2: ${{ secrets.SECRET_2 }}
          SECRET_3: ${{ secrets.SECRET_3 }}
          SECRET_4: ${{ secrets.SECRET_4 }}
          SECRET_5: ${{ secrets.SECRET_5 }}
          SECRET_6: ${{ secrets.SECRET_6 }}
          SECRET_7: ${{ secrets.SECRET_7 }}
          SECRET_8: ${{ secrets.SECRET_8 }}
          SECRET_9: ${{ secrets.SECRET_9 }}

          IS_DRAFT: true
